[theme]
base="dark"

# Primary accent for interactive elements
primaryColor = '#B1FC74'

# Background color for the main content area
backgroundColor = '#FAFFE6'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#B9D1C9'

# Color used for almost all text
textColor = '#080808'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"